/**
 * @packageDocumentation
 * @module routing/UiRoutingModule
 * @author luchik
 */
/** */

import { Component } from '@angular/core';

// Core Config
import {
    IconsListAutogeneratedInterface,
    IconsListAutogenerated,
    IconsListAutogeneratedOther
} from '@app-core/config/icons-autogenerated';
// Core libs
import { CopyToClipboard } from '@app-core/lib/utils/copy-to-clipboard/copy-to-clipboard';

/**
 * The UI page that provides the list of all the icons avaliable in the system
 */
@Component({
    selector: 'app-ui-routing-icons-page',
    templateUrl: './icons-page.component.html',
    styleUrls: ['./icons-page.component.scss'],
})
export class IconsPageComponent {
    // Icons list
    public iconsSvg: Array<string> = [];
    public iconsPng: Array<string> = [];
    public iconsGif: Array<string> = [];
    public iconSections: Array<IconsListAutogeneratedInterface> = [];

    // Controls
    public showName: boolean = true;
    public showPath: boolean = false;
    public copyOnClick: boolean = true;
    public showControls: boolean = false;

    // colors list
    public colors: Array<string> = [
        'inherit', '#f86414', '#f8b918', '#84deb5', '#36d383',
        '#96d1fb', '#3290e2', '#acb8c3', '#e4004e', '#f28aa7',
        '#9800ee'
    ];
    public color: string = '#9800ee';
    public bgColors: Array<string> = [
        'inherit', '#ccc',
    ];
    public bgColor: string = '#ccc';

    constructor(
    ) {
        const that = this;

        that.iconSections.push(IconsListAutogenerated);
        that.iconSections.push.apply(that.iconSections, IconsListAutogeneratedOther);
    }

    /**
     * Copy text to clipboard
     * @param string color
     * @returns void
     * @TODO move to libs
     */
    public copyName(val: string): void {
        if (!this.copyOnClick) {
            return;
        }
        CopyToClipboard.copy(val);
    }
}
