/**
 * @packageDocumentation
 * @module CoreModule/config
 * @author luchik
 */
/** This file is autogenerated with gulp. Use `gulp icons` to rebuild the file */

/**
 * Icons interface
 */
export interface IconsListAutogeneratedInterface {
    svgprefix: string;
    dir: string;
    svg: Array<string>;
    png: Array<string>;
    gif: Array<string>;
}

/**
 * Base Autogenerated Icons from UI folder
 */
export const IconsListAutogenerated: IconsListAutogeneratedInterface = {
    svgprefix: '',
    dir: '/ui/icons',
    svg: [
        '/challenge.svg',
        '/container.svg',
        '/user.svg',
    ],
    png: [
    ],
    gif: [
    ],
};

/**
 * Additionall Autogenerated Icons
 */
 export const IconsListAutogeneratedOther: Array<IconsListAutogeneratedInterface> = [
    {
        svgprefix: '/global/ui/logos',
        dir: '/ui/logos/',
        svg: [
            '/kiwi.svg',
            '/logo.svg',
        ],
        png: [
        ],
        gif: [
        ],
    },
];
