/**
 * Shared UI Module
 *
 * @packageDocumentation
 * @module shared/UiModule
 * @preferred
 * @author luchik
 */
/** */

import { NgModule } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatIconModule, MatIconRegistry } from '@angular/material/icon';

// Core Config
import {
    IconsListAutogeneratedInterface,
    IconsListAutogenerated,
    IconsListAutogeneratedOther
} from '@app-core/config/icons-autogenerated';

// Componens
import { InlineLoaderComponent } from './components/inline-loader/inline-loader.component';

@NgModule({
    imports: [
        CommonModule,
    ],
    exports: [
        CommonModule,
        FlexLayoutModule,
        // Material JS
        MatIconModule,
        // Pipes
        // Directives
        // Components
        InlineLoaderComponent,
    ],
    declarations: [
        // Pipes
        // Directives
        // Components
        InlineLoaderComponent,
    ]
})
export class UiModule {

    constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
        const sections: Array<IconsListAutogeneratedInterface> = [];
        sections.push(IconsListAutogenerated);
        sections.push.apply(sections, IconsListAutogeneratedOther);

        sections.forEach((section: IconsListAutogeneratedInterface) => {
            section.svg.forEach((icon: string) => {
                // const extension: string = icon.split('.').pop();
                iconRegistry.addSvgIcon(
                    'tstappi' + section.svgprefix + icon,
                    sanitizer.bypassSecurityTrustResourceUrl('/assets/images' + section.dir + icon)
                );
            });
        });
    }
}
